name: Update Language Usage Chart

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-language-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests matplotlib seaborn

      - name: Run language chart script
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          GITHUB_USERNAME: ${{ secrets.MY_USERNAME }}
        run: python scripts/language_stats.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.MY_TOKEN }}@github.com/${{ github.repository }}

          # Make sure the new file is added and commit it
          git add assets/langs.svg
          git status  # Confirm the file is tracked and ready for commit
          git commit -m "📊 Update language usage chart" || echo "No changes to commit"  # Ignore error if no changes
          git push
